### PR TITLE
Improve/theme

### PR DESCRIPTION
**Pull request by NdekoCode**
I made some improvements to the design. Here's a summary of what I did
-  Added Dark Mode: I implemented a dark mode feature that allows users to switch between light and dark themes
- Responsive Design: I made the website responsive
- Replaced Bootstrap CSS: I removed the Bootstrap CSS framework and replaced it with a simple and customized styling approach, giving the website a unique look.
- Add SPA navigation

 Please feel free to review my changes and provide any necessary input. I am available to address any concerns or make further improvements as required.

https://github.com/ever-co/ever-charts/assets/85836702/70d42b1a-29cc-4287-9ecd-c04b80f2830e

### CODE REVIEW

**Comment by NdekoCode** [comment]
if possible sir @Saif-Uz-Zaman , I replaced the card injected by JavaScript with the new card I implemented so please when you have added the static data in index.yaml, just adjust what needs to change and replace it with what corresponds to the new design

**Comment by Saif-Uz-Zaman** [comment]
@NdekoCode You should not push the `index.yaml` in the _site directory. You can check it from your local and you can add it in the .gitignore so that it will prevent you pushing this file to the repo. Otherwise, it will be problematic. Because `index.yaml` is autogenerated content while we push a new chart.

**Comment by NdekoCode** [comment]
Sorry, @Saif-Uz-Zaman it was already in .gitignore, then I forgot when I was doing the test

**Comment by Saif-Uz-Zaman** [comment]
@evereq, I have updated the icon property of the helm charts. @NdekoCode I updated the JavaScript code to align it with the `index.yaml` file.

**Pull request merged**
