### PR TITLE
Fix/style errors

### PR DESCRIPTION
**Pull request by NdekoCode**
I've corrected most of the errors except for the category filtering part, because for the moment I don't yet know the logic I'm going to apply and the filtering system we're going to consider.
- The header is fixed and the logo size is corrected.
- The logo in the footer is centered in relation to the overall page container.
- The text in the footer is also corrected.
- Category alignment is also corrected.
- For missing images @Saif-Uz-Zaman, just add the following values of the overview key next to the `icon` key:

```
Ever-Gauzy:
- icon: "https://raw.githubusercontent.com/ever-co/ever-charts/develop/_site/assets/logo-ever-gauzy.png"
- overview: "https://raw.githubusercontent.com/ever-co/ever-charts/develop/_site/assets/ever-gauzy-overview.png"
Ever-Gauzy-API:
- icon: "https://raw.githubusercontent.com/ever-co/ever-charts/develop/_site/assets/logo-ever-gauzy.png"
- overview: "https://raw.githubusercontent.com/ever-co/ever-charts/develop/_site/assets/ever-gauzy-overview.png"
Ever-Teams:
- icon: "https://raw.githubusercontent.com/ever-co/ever-charts/develop/_site/assets/logo-ever-teams.png"
- overview: "https://raw.githubusercontent.com/ever-co/ever-charts/develop/_site/assets/ever-teams-overview.png"
....
```

I tried to fix this myself but I had a linting error which is "Property overview is not allowed.yaml-schema: Helm Chart.yaml"

### CODE REVIEW

**Comment by Saif-Uz-Zaman** [comment]
@NdekoCode I don't create the `index.yaml` file. It is a system-generated file and is usually created during `helm publish`. What I can do? I Can update the properties for `Chart.yaml`. `Chart.yaml` usually looks like this,

```
apiVersion: The chart API version (required)
name: The name of the chart (required)
version: A SemVer 2 version (required)
kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
description: A single-sentence description of this project (optional)
type: The type of the chart (optional)
keywords:
  - A list of keywords about this project (optional)
home: The URL of this projects home page (optional)
sources:
  - A list of URLs to source code for this project (optional)
dependencies: # A list of the chart requirements (optional)
  - name: The name of the chart (nginx)
    version: The version of the chart ("1.2.3")
    repository: (optional) The repository URL ("https://example.com/charts") or alias ("@repo-name")
    condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
    tags: # (optional)
      - Tags can be used to group charts for enabling/disabling together
    import-values: # (optional)
      - ImportValues holds the mapping of source values to the parent key to be imported. Each item can be a string or pair of child/parent sublist items.
    alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times
maintainers: # (optional)
  - name: The maintainers name (required for each maintainer)
    email: The maintainers email (optional for each maintainer)
    url: A URL for the maintainer (optional for each maintainer)
icon: A URL to an SVG or PNG image to be used as an icon (optional).
appVersion: The version of the app that this contains (optional). Needn't be SemVer. Quotes recommended.
deprecated: Whether this chart is deprecated (optional, boolean)
annotations:
  example: A list of annotations keyed by name (optional).
```

There is no suitable place for the overview images. But there is a possibility, we can add the overview image URL in the `sources` key, as it is an array of source URLs.

What do you think @evereq ?

**Comment by evereq** [comment]
Hm, why can't we just load images from some static folder using helm chart name?? I described that before in Slack @NdekoCode @Saif-Uz-Zaman

**Comment by Saif-Uz-Zaman** [comment]
@evereq I think we can use the chart name and dynamically populate it from the assets folder. Like for 'example-chart' we can use the url like 'assets/example-chart-overciew.jpg'.

@NdekoCode

**Comment by NdekoCode** [comment]
@NdekoCode @Saif-Uz-Zaman, Already fixed.

**Pull request merged**
